### PR TITLE
Lab 7 

### PR DESCRIPTION
**Pull request by ebrarkiziloglu**
This PR includes our work for the Lab 7:

- [x] Plan for the demo next week, including data population strategy, scenario, etc. @ebrarkiziloglu @arincdemir 
- [x] Outline the software quality plan, including unit test coverage and integration testing. @fahreddinozcan #378
- [x] Document the user experience decisions made in the previous lab. @odenizddd 
- [x] Backend unit testing @semihYILMAZ37 @HutkuC @set120120 
- [x] Backend end-points @semihYILMAZ37 @HutkuC @set120120

### CODE REVIEW

**Comment by odenizddd** [comment]
I documented the user experience enhancement plans and actions [here](https://github.com/bounswe/bounswe2024group5/wiki/User-Experience-Enhancement-Decisions-and-Actions)

**Comment by ebrarkiziloglu** [comment]
@arincdemir and I added the customer presentation plan to our general wiki plan, [here](https://github.com/bounswe/bounswe2024group5/wiki/General-Plan#customer-presentation-2-planning).

We planned 2 user scenarios that we will follow in our demo. We also did brainstorming on our data population strategy and took notes in the [wiki](https://github.com/bounswe/bounswe2024group5/wiki/General-Plan#customer-presentation-2-planning).

**Comment by set120120** [comment]
We've added one unit test(with @semihYILMAZ37 and @ebrarkiziloglu ), and also some endpoints (with @semihYILMAZ37 and @HutkuC ) .

**Comment by fahreddinozcan** [comment]
The PR looks good to me, thanks for the good work everyone!

**Review by fahreddinozcan — APPROVED** [review]

**Pull request merged**
