### PR TITLE
Difficulty algorithm adjustment

### PR DESCRIPTION
**Pull request by set120120**
I've changed point-related code pieces and score of english words in db. Could you please check it?

### CODE REVIEW

**Comment by set120120** [comment]
Here is the sql code I used to determine score of English words:

```sql
UPDATE englishWords
SET word_point = 
    CASE 
        WHEN score IS NULL THEN 5000  -- NULL değerler için orta seviye
        ELSE ROUND(
            LEAST(  -- Maksimum 10000 sınırı için
                CASE
                    -- Çok kolay kelimeler (0-1)
                    WHEN score <= 1 THEN 
                        score * 1000  -- 0-1000 arası puan
                    
                    -- Kolay kelimeler (1-3)
                    WHEN score <= 3 THEN 
                        1000 + ((score - 1) * 1250)  -- 1000-3500 arası puan
                    
                    -- Orta kelimeler (3-4)
                    WHEN score <= 4 THEN 
                        3500 + ((score - 3) * 2000)  -- 3500-5500 arası puan
                    
                    -- Orta zor kelimeler (4-5.5)
                    WHEN score <= 5.5 THEN 
                        5500 + ((score - 4) * 1666.67)  -- 5500-8000 arası puan
                    
                    -- Çok zor kelimeler (>5.5)
                    ELSE 
                        8000 + ((score - 5.5) * 1333.33)  -- 8000-10000 arası puan
                END,
                10000  -- Maksimum değer sınırı
            ), 
            0
        )
    END;
```

**Comment by set120120** [comment]
points < 1500 THEN A1
points < 3500 THEN A2
points < 5000 THEN B1
points < 6500 THEN B2
points < 8500 THEN C1
points > 10000 THEN C2

Here the translation of user points to CEFR levels.

**Comment by set120120** [comment]
The updated version is:
```sql
UPDATE englishWords
SET word_point = 
    CASE 
        WHEN score IS NULL THEN 2500  -- default value
        ELSE ROUND(
            LEAST( 
                CASE
                    -- between 0-2.7 (0-500 point, A1)
                    WHEN score <= 2.7 THEN 
                        (score / 2.7) * 500
                    
                    -- between 2.7-3.15 (500-1000 point, A2)
                    WHEN score <= 3.15 THEN 
                        500 + ((score - 2.7) / (3.15 - 2.7)) * 500
                    
                    -- between 3.15-3.45 (1000-1500 point, B1)
                    WHEN score <= 3.45 THEN 
                        1000 + ((score - 3.15) / (3.45 - 3.15)) * 500
                    
                    -- between 3.45-3.80 (1500-2000 point, B2)
                    WHEN score <= 3.80 THEN 
                        1500 + ((score - 3.45) / (3.80 - 3.45)) * 500
                    
                    -- between 3.80-4.00 (2000-2500 point, C1)
                    WHEN score <= 4.00 THEN 
                        2000 + ((score - 3.80) / (4.00 - 3.80)) * 500
                    
                    -- between 4.00-7.00 (2500-5000 point, C2)
                    ELSE 
                        2500 + ((score - 4.00) / (7.00 - 4.00)) * 2500
                END,
                5000
            ), 
            0
        )
    END;
   ```

**Review by semihYILMAZ37 — APPROVED** [review]
cool work bro, thanks for your efforts!

**Pull request merged**
