### PR TITLE
Lab 5 Content

### PR DESCRIPTION
**Pull request by fahreddinozcan**
This PR contains the jobs done in the Lab 5. 

The tasks that are handled with this PR are:
- [X] Documented the W3C standards to implement: See the [wiki page](https://github.com/bounswe/bounswe2024group5/wiki/W3C-Standards).
- [X] Started WAI-ARIA Web Standard implementation #350 
- [x] #349. 
- [X] #348 . See the [wiki page](https://github.com/bounswe/bounswe2024group5/wiki/Lab-Meeting-%235-%7C-05.11.2024).

### CODE REVIEW

**Comment by ramazanoacar** [comment]
For the mobile part, we (@arincdemir , @ebrarkiziloglu ) implemented a validation mechanism for checking the words in quiz generation. We implemented it for domain specification purposes. It works as follows:

User selects a type for question (cannot enter a question without selecting type)
Starts entering a word
After this process is finished, we send a request to the backend
Backend checks if it is a valid english word
If valid -> returns true and we continue with quiz generation
If not a valid English word -> returns false and user faces a pop-up stating that the word is not a valid English word.

**Comment by ebrarkiziloglu** [comment]
There was a formatting problem in the commits' messages. Thus the co-authors were not displayed properly. We worked on the mobile commits together with @ramazanoacar and @arincdemir.

**Comment by set120120** [comment]
For the backend part we (@semihYILMAZ37 @HutkuC ) implemented the endpoint (word-checker) and also we changed the api-design.yml. We return true if word in database, false otherwise.

**Review by odenizddd — APPROVED** [review]

**Comment by HutkuC** [comment]
LGTM <3

**Pull request merged**
