### PR TITLE
Lab 8 Content

### PR DESCRIPTION
**Pull request by ebrarkiziloglu**
This PR includes our work for the lab 8.

We generate an acceptance criteria document and and report the situation of our project in terms of the following criteria:
- [x] Primary features (e.g. semantic search, user management), @ebrarkiziloglu @semihYILMAZ37 
- [x] Domain-specific features (e.g. why they're specific, how they're implemented), @arincdemir @ebrarkiziloglu 
- [x] API and its documentation (e.g. endpoints, expected inputs, outputs), @semihYILMAZ37 @set120120 @ramazanoacar 
- [x] Standard(s) being followed (e.g. its documentation, implementation), @odenizddd @fahreddinozcan 
- [x] Testing strategies (e.g. unit test coverage, integration testing, tools). @semihYILMAZ37 @set120120 @ramazanoacar

### CODE REVIEW

**Comment by ebrarkiziloglu** [comment]
I initialized the acceptance criteria document in the `doc/acceptance-criteria` path.

**Comment by ramazanoacar** [comment]
I worked on the testing strategies with @semihYILMAZ37 and @set120120

**Comment by ebrarkiziloglu** [comment]
I added the User Management subsection under the primary features section

**Review by semihYILMAZ37 — APPROVED** [review]
good job team!

**Pull request merged**
